# Generated by Django 2.2.2 on 2019-12-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_add_bus_add_route_book_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_bus',
            name='trevaltime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
